#!/bin/bash

set -e

if [ $# -ne 2 ]; then
	echo "Usage: $0 KERNEL LINASETUP" >&2
	exit -1
fi

echo "NOTE: cirith maintains different codegen repositories for each Lina setup" >&2
echo "      (e.g. this run will use $CDG_ROOTD/$2 as \$CDG_ROOTD)" >&2
echo "      The difference between each repository is more related to the memory" >&2
echo "      analyses performed by Lina (i.e. the memanalysis.rpt files might differ)" >&2
echo "      However, the manual transformation might be the same among all setups," >&2
echo "      therefore before manipulating the kernel, check if there isn't already an" >&2
echo "      implemented kernel with the same code (e.g. f200_0.1.0.0_...), same manual" >&2
echo "      transforms enabled (e.g. rbwUnroll1_explVec0) from the same kernel and" >&2
echo "      experiment. More specifically, check for these folders:" >&2
echo "" >&2
echo "      \$CDG_ROOTD/*/<experiment>/<kernel>/<code>/<rbwUnrollX_explVecY>/" >&2
echo "" >&2
echo "      if such similar project is found, its kernel files can probably be reused" >&2
echo "      (manual copy/paste from one repo to another is necessary, I'm sorry for the" >&2
echo "      inconvenience :( we are under construction)" >&2
_CDG_ROOTD=$CDG_ROOTD

echo -ne "\n"\
"outcomes/experiment1/$1: outcomes/experiment1/$1.out\n"\
"	rm -rf outcomes/experiment1/$1\n"\
"	./paretogen.py prepare experiment1\n"\
"	./paretogen.py decide experiment1\n"\
"\n"\
"outcomes/experiment1/$1.out: csvs/experiment1/$1.csv\n"\
"	rm -rf outcomes/experiment1\n"\
"	./paretogen.py pareto experiment1\n" | env CDG_ROOTD=$_CDG_ROOTD/$2 make -f -